### ISSUE TITLE
Bug from potential TOR attacks?

### ISSUE THREAD

**Issue by tamlthari** [torproject/nyx#13]
When run `nyx` on macOS CLI, I was able to view the first 2 reports (connection details, node circuit infos, configs), then `nyx` crashes with error `abort trap: 6` . is this a sign of TOR attacks? Also there was no connection details. I know there was explanations but this is fyi. TKS! 
Also I just noticed that on the first report, it read 'Relaying disabled', is this normal in your opinion?

**Comment by atagar** [comment]
Hi tamlthari, sorry for the delay (was on vacation). No, this is **not** indicating an attack nor related to Nyx. This error response (`abort trap: 6`) is C specific so this most likely it is coming from your python interpreter. Please see [this](https://github.com/pypa/pip/issues/7254) for some ideas.

Feel free to reopen if you have any other questions.
