### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hans91399** [torproject/nyx#16]
Title. Has been working good for a month, now I'm getting "segmentation fault". happens through SSH as well. Have removed and reinstalled.

**Comment by atagar** [comment]
Hi Hans. As Guido once said, "If applications stacktrace that's your problem, if they segfault it's mine."

Nyx is a Python application. Segfaults indicate a problem in your interpreter. If you have a coredump or other diagnostic information then please report it upstream: https://bugs.python.org/
