### ISSUE TITLE
FAQ webpage unavailable without javascript

### ISSUE THREAD

**Issue by atagar** [torproject/nyx#21]
[Our website](https://nyx.torproject.org/) tries to fall back when JS is unavailable, but our FAQ is entirely missing without JS.

Without JS we can't toggle the visibility of items, but the information should be available in some form.

**Comment by saizai** [comment]
Simple answer: make it visible by default, use js to close it.

**Comment by saizai** [comment]
Also, you seemed to not be using current jQuery hooks for some reason — e.g.  custom toggle code when jQuery has a function for that which works just fine. 

I couldn't tell why. Was I missing something? AFAICT the old toggle code was completely unnecessary, so I just deleted it with the replacement. If there's some scenario I missed that justified the custom stuff please LMK.

I tested my patch by injection / DOM console manipulation. Worked perfectly. You should test the merged version on your own browser, though.

**Comment by atagar** [comment]
Thanks Sai! [Pushed a variant of your fix.](https://gitweb.torproject.org/nyx.git/commit/?id=3a53a21)

Unfortunately your change had a few small issues...

* It removed the toggleFaq function without removing all of it usage.
* It removed styles_no_js.css without removing its import.
* It broke FAQ anchors (described below).

> I couldn't tell why. Was I missing something?

Yes and no. Honestly I don't recall why I used `animate()` rather than `toggle()`, but it's important for the url to change when you click an answer (for example, `index.html#what_is_nyx`), that way you can send a link that answers someone's question.
