### ISSUE TITLE
Delete packaging & release branches

### ISSUE THREAD

**Issue by saizai** [torproject/nyx#29]
They're 9 years out of date.

**Comment by atagar** [comment]
Thanks Sai, good catch. You're absolutely right that we should delete them. I'll need to engage with our TPO git admins for assistance with that (iirc we disallow branch deletions on our canonical repos).

**Comment by atagar** [comment]
Filed a downstream ticket to request this: https://gitlab.torproject.org/tpo/tpa/team/-/issues/40073

**Comment by atagar** [comment]
The packaging and release branches are now deleted in both the TPO repository and this one.
