### ISSUE TITLE
logged_events fails when copying from nyx's displayed events filter

### ISSUE THREAD

**Issue by saizai** [torproject/nyx#31]
1. open nyx, first page -> e -> select various event types.
2. observe in nyx: `Events (TOR/NYX NOTICE-ERR, ADDRMAP, CONF_CHANGED, GUARD, NETWORK_LIVENESS, SIGNAL, STATUS_CLIENT, STATUS_GENERAL):`
3. infer that those are recognized logged_events flags, so put those in ~/.nyx/config
```
logged_events NOTICE, WARN, ERR, NYX_NOTICE, NYX_WARNING, NYX_ERROR, ADDRMAP, CONF_CHANGED, GUARD, NETWORK_LIVENESS, SIGNAL, STATUS_CLIENT 
```
4. Sad trombone. Result (in nyx)
```
 Your --log argument had the following events tor doesn't recognize:  WARN,  ERR,  NYX_NOTICE,  NYX_WARNING,  NYX_ERROR,  ADDRMAP,  CONF_CHANGED,  GUARD,  NETWORK_LIVENESS,  SIGNAL,  STATUS_CLIENT
```

**Comment by atagar** [comment]
Thanks Sai! Fixed...

https://gitweb.torproject.org/nyx.git/commit/?id=1d5ecdf
