### ISSUE TITLE
Old package for debian or not? 

### ISSUE THREAD

**Issue by PaS3** [torproject/nyx#40]
```
nyx version 2.1.0 (released January 12, 2019)

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Tor version 0.4.5.10.
```

User interface reads the tor version as "obsolete":
```
nyx - lada (Linux 4.19.0-17-amd64)         Tor 0.2.9.8 (obsolete)
```

**Comment by atagar** [comment]
Hi PaS3, it looks like you have multiple copies of tor on your system (0.2.9.8 and 0.4.5.10). Version information comes from the control port (ie. the running instance of tor that nyx connects to).

Did you have any other questions?

**Comment by PaS3** [comment]
I did not see it but it was somehow installed long ago or by torchat. 

Thank you,

**Comment by atagar** [comment]
No problem. :)
