### ISSUE TITLE
Figured you'd want to know that I've got Nyx to run natively on Windows (mostly)

### ISSUE THREAD

**Issue by DandelionSprout** [torproject/nyx#53]
Whether it'd be in the interest of the dev team, end-users, both, or neither, I've managed to get Nyx to run on Windows, thus filling a potential user demographic considering how https://nyx.torproject.org/#download states the upstream project doesn't support Windows.

The details, patch-files, and installation notes are at https://github.com/DandelionSprout/NyxForWindows, and takes the form of 2 files to overwrite a couple files from the Python pip version with, and is not a full fork or redistribution of the entire program.

I've done my utmost to ensure compliance with GPL-3.0, as verbose as that licence is.

**Comment by atagar** [comment]
Thanks Imre, that looks great! I left Tor a year ago so Nyx isn't receiving any love at preset but there's several great things here. I wasn't aware of the windows-curses package - that's quite a game changer.

Merging this with the main ticket for Windows support: https://github.com/torproject/nyx/issues/4
