### ISSUE TITLE
Does Nyx modify/remove/add any files to /var/lib/tor?

### ISSUE THREAD

**Issue by Jayto1** [torproject/nyx#54]
I'm curious if a relay with nyx would have the same /var/lib/tor directory as one without nyx? So my question is does nyx interact with this directory at all? Thanks!

**Comment by atagar** [comment]
Hi Jayto. Generally speaking no, nyx does not modify that directory. However, it contains some features that can do so. For example, if you edit your tor configuration (page 3 of the interface) then save that issues a SAVECONF command to tor which writes a new torrc. If your torrc is in /var/lib/tor then it would have the effect of writing there.

Feel free to reopen if you have any other questions.

**Comment by Jayto1** [comment]
@atagar Thanks for your response! So if I wanna backup my relays /var/lib/tor/keys directory should I do so before or after I install nyx or should it not make a difference? Thanks again.

**Comment by atagar** [comment]
Nothing in Nyx interacts with the keys subdirectory so it shouldn't matter.
