### ISSUE TITLE
By default Nyx cant run without sudo on Debain

### ISSUE THREAD

**Issue by Jayto1** [torproject/nyx#55]
Steps I used to get it working on Debian

1. add `CookieAuthFileGroupReadable 1` to  `/etc/tor/torrc`
2. sudo usermod -aG debian-tor $USER
3. sudo systemctl restart tor
4. exit

After I logged back in and tor was successfully restarted I was able to use Nyx without sudo

Different OS with the same issue https://github.com/torproject/nyx/issues/37

**Comment by atagar** [comment]
Closing as a duplicate of https://github.com/torproject/nyx/issues/24
